# This is a basic workflow to help you get started with Actions

name: Checkmarx AST Scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@v0.28
        with:
          base_uri: https://eu.ast.checkmarx.net/
          cx_tenant: asean_2021_08
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          scan_types: sast,sca,kics

      # Build the JavaVulnerableLab project
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo End of Github Action!
